### ISSUE TITLE
Is it possible for broker to implement exactly once delivery?

### ISSUE THREAD

**Issue by snowwolf007cn** [knative-sandbox/eventing-kafka-broker#1715]
**Problem**
I think at least once is not enough in some scenarios, and Kafka can support exactly once by its transaction.
Is it possible for the broker to implement exactly once?

**Comment by jhill072** [comment]
This seems to be first-class support by Kafka now: https://www.confluent.io/blog/transactions-apache-kafka/

I wonder if this would be useful as another type of delivery order: `EXACTLY_ONCE`, which would imply the guarantees from `ORDERED` but will also provide the guarantee of exactly once reply events. Based on that article, the target use case for transactions is during the `read-process-commit` interactions, and as such this is only really useful when the reply is to be published back to Kafka.

I'm not sure that really provides the more generic "exactly once" semantics though, since it is still possible for an event to be consumed more than once (meaning any side effects from the consumer would happen again), but the guarantee is the reply event will only be published once.

I'd love to be wrong on this, as I am interested in achieving this possibility.
