### ISSUE TITLE
How to specify resource requests and limits for KafkaSource?

### ISSUE THREAD

**Issue by niels-busch-maersk** [knative-sandbox/eventing-kafka-broker#1967]
**Describe the bug**
How do you specify resource requests and limits for KafkaSource? It's not documented.

 **Expected behavior**
 KafkaSource gets OOM killed because I don't know how to specify resource limits.

 **To Reproduce**
Run KafkaSource with 256Mb memory limit. It will be OOM killed.

 **Knative release version**
1.2.0

 **Additional context**
On my company platform the default resource limits are low. We have to request resources (CPU, Memory) in the spec definition.

**Comment by pierDipi** [comment]
Hi @niels-busch-maersk, thanks for reporting!

This is highly dependent on the actual workloads you're running (how many Kafka sources, events/second, event size, etc) and that's the reason we're not setting limits and requests by default.

Here is some info to help, but I'd recommend running your own tests since your mileage may vary.

---

This is in OpenShift.

I have an idle kafka-source-dispatcher (just started at 172 MiB):

![image](https://user-images.githubusercontent.com/33736985/157011492-131516d6-989a-470c-a188-944c50883572.png)

Now, I'm processing 100 events/s:

![image](https://user-images.githubusercontent.com/33736985/157012375-804b6c54-a568-47ef-b69e-2effaa60f6bd.png)

the memory usage goes at ~271MiB

![image](https://user-images.githubusercontent.com/33736985/157012604-112a490b-0340-4f6a-87b0-6487664c162a.png)

**Comment by niels-busch-maersk** [comment]
Thanks @pierDipi My question was more if it's possible to specify the resource requests and limits for the KafkaSource? And if so, how?

**Comment by pierDipi** [comment]
You need to patch the [`eventing-kafka-source.yaml` artifact](https://github.com/knative-sandbox/eventing-kafka-broker/releases/download/knative-v1.2.3/eventing-kafka-source.yaml). 
There is a deployment called `kafka-source-dispatcher` where you can set your requests and limits.
