### ISSUE TITLE
In Source example, failure mounting "contract-resources" volume

### ISSUE THREAD

**Issue by kpassapk** [knative-sandbox/eventing-kafka-broker#2584]
**Describe the bug**

I'm going through the [example][ks], with MiniKube and Strimzi; YAML file installation.

The example output in the "Installing Kafka Source" section lists two deployments, but the latest version of the YAML files actually launches `kafka-source-dispatcher` as a StatefulSet. It fails to launch cleanly with

```
MountVolume.SetUp failed for volume "contract-resources" : configmap "kafka-source-dispatcher-0" not found
```

 **Expected behavior**
The Kafka Source should start without errors.

 **To Reproduce**
The installation procedure and YAML files are in this [repo][mine].

 **Knative release version**
v1.7.0

**Additional context**

Two issues likely here:

1. Documentation out fo date, should reflect the StatefulSet.
2. Possibly a missing instruction on the contents of this configmap.

I have gone through the installation a few times to figure out if I had missed a step and failed to install one of the required resources before getting to the source installation step.

[ks]: https://knative.dev/docs/eventing/sources/kafka-source/#installing-kafka-source
[mine]: https://github.com/kpassapk/knative-kafka

**Comment by pierDipi** [comment]
Hi @kpassapk, thanks for reporting, the warning event can be ignored, the `kafka-source-dispatcher` stateful set when there are no resources will be scaled to 0 so that warning is temporary.

regarding "Documentation out fo date, should reflect the StatefulSet." good catch, would you mind contributing to this change in the knative/docs repository?
