### ISSUE TITLE
Standalone KafkaSink installation

### ISSUE THREAD

**Issue by lionelvillard** [knative-sandbox/eventing-kafka-broker#286]
**Problem**
KafkaSink requires Knative Eventing, eventing-kafka-controller and eventing-kafka-broker to be installed.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.
kubectl apply -f eventing-kafka-sink.yaml should be enough to install KafkaSink

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by lionelvillard** [comment]
Correction: `eventing-kafka-broker` is not needed.

**Comment by pierDipi** [comment]
It makes sense to me. 

Today you can:
1. create the namespace `knative-eventing`
1. remove the config-logging volume from the controller deployment in `eventing-kafka-controller` - (and that's an issue: https://github.com/knative-sandbox/eventing-kafka-broker/issues/287)
1. apply `eventing-kafka-controller.yaml`
1. apply `eventing-kafka-sink.yaml`

The controller will logs errors like the following since it can't find the broker CRD and the trigger CRD:
```
E1012 15:54:11.841031       1 reflector.go:178] k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible/tools/cache/reflector.go:125: Failed to list *v1.Broker: the server could not find the requested resource (get brokers.eventing.knative.dev)
E1012 15:54:16.444965       1 reflector.go:178] k8s.io/client-go@v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible/tools/cache/reflector.go:125: Failed to list *v1.Trigger: the server could not find the requested resource (get triggers.eventing.knative.dev)
```
That can be fixed by only applying the Broker and Trigger CRD if they haven't been installed yet.

---

Also, in theory, by changing the namespace of all resources in both `eventing-kafka-sink.yaml` and `eventing-kafka-controller.yaml`, and changing the `SINK_DATA_PLANE_CONFIG_MAP_NAMESPACE` env variable of the `kafka-controller` deployment people should be able to install it in another namespace.

---

Questions:
- Is that enough for you? 
- Or do you want a single artifact that is a combination of `eventing-kafka-controller.yaml` and `eventing-kafka-sink.yaml`? 
- Or do you want an env var to disable the `broker` and the `trigger` reconciler?

**Comment by lionelvillard** [comment]
that's what I'm currently doing but I think it'd be nice to have only one artifact. I don't care about disabling `broker` and `trigger` reconcilers.

**Comment by slinkydeveloper** [comment]
cc @matzew to join this discussion

**Comment by slinkydeveloper** [comment]
> Or do you want a single artifact that is a combination of eventing-kafka-controller.yaml and eventing-kafka-sink.yaml?

I think splitted is fine: with a single one we'll the to ship 3 different ones: sink, broker, sink + broker which imo doesn't make any sense.

**Comment by matzew** [comment]
OK, I think for users it would be nice if we have, different files ? 

I mean, in eventing we also have the "eventing", which contains all ? 

Can we have:

* `eventing-kafka-broker.yaml`
* `eventing-kafka-controller.yaml`
* `eventing-kafka-sink.yaml`

and adding:
* `eventing-kafka.yaml` (that contains all)

**Comment by pierDipi** [comment]
Ok, from the thump ups, the agreement is to have a single bundle for all components called `eventing-kafka.yaml`.

/help
/area release
