### ISSUE TITLE
Use reproducable consumergroup name for Triggers

### ISSUE THREAD

**Issue by EndPositive** [knative-sandbox/eventing-kafka-broker#3020]
**Problem**
Currently a trigger on a kafka broker creates a consumergroup with the trigger k8s uid as the name. When the Trigger is recreated in Kubernetes, the new Trigger uid will be used to create a consumergroup. This results in a loss of consumergroup offset. In addition, the usage of only a uid as a consumergroup name is less than ideal in terms of monitoring as it requires knowing the k8s uid to resource mapping.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
System Integrator

**Exit Criteria**
The consumergroup name can be manually overriden in the k8s trigger definition OR or default to a reproducable and identifyable name.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Slack discussion: https://cloud-native.slack.com/archives/C04LMU33V1S/p1679500999809559

**Comment by pierDipi** [comment]
To solve this problem and making sure this is not a breaking change we can:

1. Add a configuration to [config-kafka-features](https://github.com/knative-sandbox/eventing-kafka-broker/blob/main/control-plane/config/eventing-kafka-broker/200-controller/100-config-kafka-features.yaml) that is a Go template of trigger's metadata, for example: `triggers.consumergroup.template: {{ .Id }}`
2. In the trigger reconciler, we will:
    1. read that configuration
    2. execute the Go template with the trigger metadata passed as input
    3. save the output in `trigger.status.annotations[group.id]` only if that status's annotation is not present
    4. Use `trigger.status.annotations[group.id]` for initializing the offset or passing the consumer group id to the data plane
5. In the next release, we can migrate to use: `triggers.consumergroup.template: triggers-{{ .Namespace }}-{{ .Name }}` since the condition on `iii` will make sure that existing triggers won't be modified but new ones will use the more friendly consumer group ids

What do you think?

**Comment by matzew** [comment]
Thanks for the proposal, @pierDipi sounds like a good approach!

**Comment by EndPositive** [comment]
Hi! If I understand correctly, you aim to create an intermediate release for retrieving the consumergroup name and setting the annotation. However, if someone would skip the release that migration process would break. In addition, using the `{{ . .Id }}`, in iii you would still get a new consumergroup whenever the trigger is recreated, losing the offset again.  I propose the following:

1. Add a configuration to [config-kafka-features](https://github.com/knative-sandbox/eventing-kafka-broker/blob/main/control-plane/config/eventing-kafka-broker/200-controller/100-config-kafka-features.yaml) that is a Go template of trigger's metadata with a default: `triggers.consumergroup.template: knative-trigger-{{ .Namespace }}-{{ .Name }}`
2. In the trigger reconciler, we will:
    1. If `trigger.status.annotations[group.id]` is set, skip to `iii`.
    2. attempt to get consumergroup with name `Id`. If it exists, set `trigger.status.annotations[group.id]` to that `Id`. If it does not exist, execute the Go template with the trigger metadata passed and set `trigger.status.annotations[group.id]` to its result.
    3. Use `trigger.status.annotations[group.id]` for initializing the offset or passing the consumer group id to the data plane
3. After some amount of release, we can get rid of `ii` and always use the Go template as a consumergroup name generator.

**Comment by pierDipi** [comment]
> However, if someone would skip the release that migration process would break

This is not really supported by Knative nor Kubernetes, so I don't think it should be a problem.

>  In addition, using the {{ . .Id }}, in iii you would still get a new consumergroup whenever the trigger is recreated

True, however, that's exactly what we have today.

> 3. After some amount of release, we can get rid of ii and always use the Go template as a consumergroup name generator.

What's I'd like to see is that since we allowing people to set their own consumer group format then for support requests or questions I found useful to have the annotation on the Trigger always, even in the future.

In addition, we cannot get rid of the annotation because we need to persist/remember that a trigger is using a specific consumer group id, even when people change it in the template.
For example, I can change the template and then I get all the existing triggers with a new consumer group id and all of them will lose their offsets tracking.

Except for point 3 where I have the concerns described above, I'm fine with your approach too
