### ISSUE TITLE
Linear or Exponential retry policy is the default one?

### ISSUE THREAD

**Issue by slinkydeveloper** [knative-sandbox/eventing-kafka-broker#746]
Per https://github.com/golang/protobuf/issues/258#issuecomment-261947335 and https://developers.google.com/protocol-buffers/docs/proto3#enum, we need to make sure that in the protobug contract the enum 0 value is the actual default. It seems to me that `Linear` should be the defaylt back off policy, right?

```
enum BackoffPolicy {

  // Exponential backoff policy
  Exponential = 0;

  // Linear backoff policy
  Linear = 1;
}
``` 

So we should change this to:

```
enum BackoffPolicy {

  // Linear backoff policy
  Linear = 0;

  // Exponential backoff policy
  Exponential = 1;
}
```

I was bitten by this while working on #701, because I set `ORDERED` as the 0 value.

**Comment by pierDipi** [comment]
> It seems to me that Linear should be the defaylt back off policy, right?

Why is that? 

Note that this is the default value of another defaulting mechanism https://github.com/knative/eventing/blob/c42772d75cc01d824817ef5491931e990fb34fae/pkg/apis/eventing/v1/broker_defaults.go#L38-L55 that happens at the webhook level.

**Comment by pierDipi** [comment]
> So we should change this to:
> ```
> enum BackoffPolicy {
> 
>  // Linear backoff policy
>  Linear = 0;
>
>  // Exponential backoff policy
>  Exponential = 1;
> }
> ```

This is a super breaking change with a no real benefit :)

I would rather set it in the controller.

**Comment by slinkydeveloper** [comment]
> Note that this is the default value of another defaulting mechanism https://github.com/knative/eventing/blob/c42772d75cc01d824817ef5491931e990fb34fae/pkg/apis/eventing/v1/broker_defaults.go#L38-L55 that happens at the webhook level.

Yes but from what i see, it doesn't default the backoffpolicy when empty. So we can choose it ourselves, but my point here is that we have to choose one: because protobuf doesn't distinguish between empty and the first value, if there is no value, the first one is always assumed. So now, when the user doesn't configure the backoffpolicy, it goes exponential by default. Hence this issue, since it seems reasonable to me to use linear as default policy (the one the user expect as default i guess)

**Comment by pierDipi** [comment]
> it goes exponential by default. Hence this issue, since it seems reasonable to me to use linear as default policy (the one the user expect as default i guess)

I chose exponential back then because we're turning a high throughput pull-based system into a push-based system with no back pressure (yet?), so applications must be really scalable to keep up with the load, and while exponential backoff might lead to long backoff times, gives the advantage of letting downstream services more time to recover, hence better delivery guarantees since the span from the first retry to the last one is longer.

> the one the user expect as default i guess

Why do you think this? 
There is a tradeoff here of course and it just depends on what kind of application users are building, so for me, exponential backoff is fine as default for the reasons outlined above.

WDYT?

**Comment by slinkydeveloper** [comment]
Sounds good to me!
