### ISSUE TITLE
Knative supports the SASL mechanisms PLAIN in the document, but actually not.

### ISSUE THREAD

**Issue by obailiumingo** [knative-sandbox/eventing-kafka-broker#794]
**Problem**
when I read knative doc v0.22.0, it show that 
```
Knative supports the following SASL mechanisms:

PLAIN
SCRAM-SHA-256
SCRAM-SHA-512
```
but when I use it, I get an error 
`invalid SASL mechanism, expected SCRAM-SHA-256 or SCRAM-SHA-512`

when I read code ,I found that:
```
    final var SASLMechanism = credentials.SASLMechanism();
    if (is(SecurityProtocol.SASL_PLAINTEXT, securityProtocol)) {
      if (isInvalidSASLMechanism(SASLMechanism)) {
        return "Security protocol " + securityProtocol.name + ": invalid SASL mechanism, expected SCRAM-SHA-256 or SCRAM-SHA-512 got " + SASLMechanism;
      }
      if (anyBlank(credentials.SASLUsername(), credentials.SASLPassword())) {
        return "Security protocol " + securityProtocol.name + ":  invalid SASL username or password";
      }
      return null;
    }
```
so  could you add PLAIN  mechanisms in next version ?

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by pierDipi** [comment]
Hi :wave:, thanks for reporting!

Unfortunately, our CI environment doesn't support SASL/PLAIN, so we're not testing this end-to-end.

We just need to expand the list here:

https://github.com/knative-sandbox/eventing-kafka-broker/blob/2d3829cf8b868585a62fcb94a8bb2e106ad2c29d/data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidator.java#L82-L84

since we already have the logic to handle SASL/PLAIN here:

https://github.com/knative-sandbox/eventing-kafka-broker/blob/2d3829cf8b868585a62fcb94a8bb2e106ad2c29d/data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KafkaClientsAuth.java#L66-L71

/good-first-issue

**Comment by obailiumingo** [comment]
> Hi 👋, thanks for reporting!
> 
> Unfortunately, our CI environment doesn't support SASL/PLAIN, it only supports SASL/SCRAM, so we're not testing this end-to-end.
> 
> We just need to expand the list here:
> 
> https://github.com/knative-sandbox/eventing-kafka-broker/blob/2d3829cf8b868585a62fcb94a8bb2e106ad2c29d/data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/CredentialsValidator.java#L82-L84
> 
> since we already have the logic to handle SASL/PLAIN here:
> 
> https://github.com/knative-sandbox/eventing-kafka-broker/blob/2d3829cf8b868585a62fcb94a8bb2e106ad2c29d/data-plane/core/src/main/java/dev/knative/eventing/kafka/broker/core/security/KafkaClientsAuth.java#L66-L71
> 
> /good-first-issue

thank you for replying. I get it.
